In [1]:
import numpy as np
import pandas as pd


# Read data

In [51]:
path = '../data/Exercises_SS22/sleeplab_dataset_10hz/patient_29_male_7_years/BeinLi_10HZ.csv'
label_path = '../data/Exercises_SS22/sleeplab_dataset_10hz/patient_29_male_7_years/sleep_staging.csv'

In [52]:
from numpy import genfromtxt
array = genfromtxt(path, delimiter=',', skip_header=1)
label = genfromtxt(label_path, delimiter=',')

In [17]:
def window(a, w = 4, o = 2, copy = False):
    sh = (a.size - w + 1, w)
    st = a.strides * 2
    view = np.lib.stride_tricks.as_strided(a, strides = st, shape = sh)[0::o]
    if copy:
        return view.copy()
    else:
        return view

In [53]:
array = np.transpose(array)
label.shape

(1093, 3)

In [54]:
label

array([[      nan,       nan,       nan],
       [1.000e+00,       nan,       nan],
       [2.000e+00,       nan,       nan],
       ...,
       [1.090e+03,       nan,       nan],
       [1.091e+03,       nan,       nan],
       [1.092e+03,       nan,       nan]])

In [47]:
print(window(array))

[[  0.   0.   0.   0.]
 [  0.   0.   0.  -6.]
 [  0.  -6.  78. -78.]
 ...
 [ -2.  -1.  -1.   2.]
 [ -1.   2.  -2.   0.]
 [ -2.   0.   1.   2.]]
